site_name: Guide Call Connect pour les utilisateurs
site_url: https://ccguide.radapel.be
theme:
  name: material
  language: fr
  palette: 
    scheme: slate
    primary: purple
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
  