site_name: Guide Call Connect
site_url: https://ccguide.radapel.be
theme:
  icon: 
    logo: material/apple-keyboard-command
  favicon: images/favicon.png
  name: material
  language: fr
  palette: 
    scheme: slate
    primary: purple
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.tabs.link
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

nav:
  - Accueil: https://ccguide.radapel.be
  - Administrateur:
    - 'Pour commencer':
      - "La page de la plate-forme": Administrateur/username.md
      - "La page d'accueil": Administrateur/home.md
    - "Flux d'appels":
      - 'Accueil': Administrateur/callflow_info.md
      - 'Menu Vocal Interactif (IVR)': Administrateur/ivr.md
    - 'Calendriers':
      - 'Description': Administrateur/calendar_info.md
      - "Création d'un calendrier": Administrateur/calendar_create.md
      - 'Déviation de nuit': Adminstrateur/calendar_nightfwd.md
  - Utilisateur:
    - 'Pour commencer':
      - 'Identifiant': Utilisateur/username.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.blocks.caption

copyright: Copyright &copy; 2024 Pelgrims Jean-François

extra:
  generator: true
  social:
    - icon: material/apple-keyboard-command
      link: https://www.proximus.be
    - icon: material/youtube
      link: https://www.youtube.com/@proximus
    
  